config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "home#index"
  devise_scope :user do
    get 'users/sign_out' => 'devise/session#destroy'
  end

  root 'pages#index'
  # add root get search to entity#search
  get 'search', to: 'trips#search'
  resources :companies,
            :passengers,
            :service_types,
            :tickets,
            :train_types,
            :trips

  namespace :admin do
    get 'dashboard', to: 'pages#dashboard'
    get 'board', to: 'types#board'
    resources :employees,
              :passengers,
              :positions,
              :tickets,
              :trips
  end

  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :position

  delegate :name_position, to: :position
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :user

  scope :by_user, ->(user) { where(user_id: user.id) }
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employees
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :passenger
  belongs_to :trip
  belongs_to :employee

  has_one :user, through: :passenger

  scope :by_user, ->(user) { joins(passenger: :user).where(user: { id: user.id }) }
end

app/models/train_type.rb
class TrainType < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :service_type
  belongs_to :train_type
  belongs_to :company

  delegate :name_service_type, to: :service_type
  delegate :name_train_type, to: :train_type
  delegate :name_company, to: :company

  scope :number_trip_asc, -> { order(:number_trip) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :passengers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/employees_controller.rb
module Admin
  class EmployeesController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_employee, only: %i[edit update show destroy]

    def index
      @employees = Employee.all.order(created_at: :desc)
    end

    def show

    end

    def new
      @employee = Employee.new
    end

    def edit
    end

    def create
      @employee = Employee.new(employee_params)

      if @employee.save
        redirect_to admin_employee_url(@employee)
      else
        render :new
      end
    end

    def update
      respond_to do |f|
        if @employee.update(employee_params)
          f.html { redirect_to admin_employee_url(@employee) }
        else
          f.html { render :edit }
        end
      end
    end

    def destroy
      @employee.destroy

      respond_to do |f|
        f.html { redirect_to admin_employees_url }
      end
    end

    private

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :name_station, :position_id)
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @user = current_user
  end

  def about; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[edit update show destroy]

  def index
    @tickets = Ticket.by_user(current_user).order(created_at: :desc)
  end

  def show; end

  def new
    @employee_ticket = Employee.all.pluck(:id).to_a.sample
    @passenger_by_user = Passenger.all.by_user(current_user)
    @ticket = Ticket.new(employee_id: @employee_ticket)
  end

  def edit
    @passenger_by_user = Passenger.all.by_user(current_user)

  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.employee_id ||= Employee.all.pluck(:id).to_a.sample
    @passenger_by_user = Passenger.all.by_user(current_user)
    if @ticket.save
      p @ticket
      redirect_to ticket_url(@ticket)
    else
      render :new
    end
  end

  def update
    @passenger_by_user = Passenger.all.by_user(current_user)

    respond_to do |f|
      if @ticket.update(ticket_params)
        f.html { redirect_to ticket_url(@ticket) }
      else
        f.html { render :edit }
      end
    end
  end

  def destroy
    @passenger_by_user = Passenger.all.by_user(current_user)

    @ticket.destroy

    respond_to do |f|
      f.html { redirect_to tickets_url }
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:passenger_id, :trip_id, :employee_id)
  end

  def set_ticket
    @ticket = Ticket.by_user(current_user).where(id: params[:id]).first
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = params[:q].blank? ? Trip.all.order(created_at: :desc) : Trip.all.number_trip_asc
  end

  def show
    @trip = Trip.where(id: params[:id]).first
  end

  def search
    @trip = Trip.where("number_trip = ?", params[:q]).first
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/train_types_helper.rb
module TrainTypesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/admin/employees/_employee.html.erb
<div class="row">
  <div class="col-xs-8">
    <div class="well well-lg">
      <div class="review-title">
        <p>
          <strong>First name:</strong>
          <%= employee.first_name %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Last name:</strong>
          <%= employee.last_name %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Station name:</strong>
          <%= employee.name_station %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Position:</strong>
          <%= employee.position.name_position %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/admin/employees/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: [ :admin, @employee ], :html => {class: "form-horizontal", role: "form"}) do |form| %>
      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :first_name %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :first_name, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :last_name %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :last_name, rows: 10, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :name_station %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :name_station, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :position_id %>
        </div>
        <div class="col-sm-3">
          <%= form.number_field :position_id, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= form.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/employees/create.html.erb
<h1>Admin::Employees#create</h1>
<p>Find me in app/views/admin/employees/create.html.erb</p>

app/views/admin/employees/destroy.html.erb
<h1>Admin::Employees#destroy</h1>
<p>Find me in app/views/admin/employees/destroy.html.erb</p>

app/views/admin/employees/edit.html.erb
<h1>Edit employee</h1>
<%= render 'admin/employees/form', employee: @employee %>
<br>
<div>
  <%= link_to "Back to other employees", admin_employees_path, class: "btn btn-xs btn-primary" %>
</div>

app/views/admin/employees/index.html.erb
<h1>Table of employees</h1>

<%#= link_to "Add new room", new_admin_room_path %>
<style>
    table, th, td {
        border: 2px solid white;
    }

    th, td {
        background-color: #DCDCDC;
    }
</style>
<table class="table">
  <tr>
    <th scope="col">ID Employee</th>
    <th scope="col">First name</th>
    <th scope="col">Last name</th>
    <th scope="col">Station</th>
    <th scope="col">Position</th>
  </tr>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.id %></td>
      <td><%= link_to employee.first_name, admin_employee_url(employee) %></td>
      <td><%= employee.last_name %></td>
      <td><%= employee.name_station %></td>
      <td><%= employee.name_position %></td>
    </tr>
  <% end %>
</table>

app/views/admin/employees/new.html.erb
<h1>New employee</h1>
<%= render "form", employee: @employee %>
<br>
<div>
  <%= link_to "Back to other employees", admin_employees_path, class: "btn btn-xs btn-primary" %>
</div>

app/views/admin/employees/show.html.erb
<%= render 'admin/employees/employee', employee: @employee %>
<div>
  <%= link_to "Back", admin_employees_path, class: "btn btn-xs btn-primary" %>
  <%= link_to "Edit", edit_admin_employee_path(@employee), class: "btn btn-xs btn-success" %>
  <%= button_to "Delete", admin_employee_path(@employee), method: :delete, class: "btn btn-xs btn-danger" %>
</div>

app/views/admin/employees/update.html.erb
<h1>Admin::Employees#update</h1>
<p>Find me in app/views/admin/employees/update.html.erb</p>