config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "home#index"
  devise_scope :user do
    get 'users/sign_out' => 'devise/session#destroy'
  end

  root 'pages#index'
  # add root get search to entity#search
  get 'search', to: 'trips#search'
  resources :companies,
            :passengers,
            :service_types,
            :tickets,
            :train_types,
            :trips

  namespace :admin do
    get 'dashboard', to: 'pages#dashboard'
    get 'board', to: 'types#board'
    resources :employees,
              :passengers,
              :positions,
              :tickets,
              :trips
  end

  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :position

  delegate :name_position, to: :position
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :user

  scope :by_user, ->(user) { where(user_id: user.id) }
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employees
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :passenger
  belongs_to :trip
  belongs_to :employee

  has_one :user, through: :passenger

  scope :by_user, ->(user) { joins(passenger: :user).where(user: { id: user.id }) }
end

app/models/train_type.rb
class TrainType < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :service_type
  belongs_to :train_type
  belongs_to :company

  delegate :name_service_type, to: :service_type
  delegate :name_train_type, to: :train_type
  delegate :name_company, to: :company

  scope :number_trip_asc, -> { order(:number_trip) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :passengers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/trips_controller.rb
module Admin
  class TripsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_trip, only: %i[edit update show destroy]

    def index
      @trips = Trip.all.order(created_at: :desc)
    end

    def show

    end

    def new
      @trip = Trip.new
    end

    def edit
    end

    def create
      @trip = Trip.new(trip_params)

      if @trip.save
        redirect_to admin_trip_url(@trip)
      else
        render :new
      end
    end

    def update
      respond_to do |f|
        if @trip.update(trip_params)
          f.html { redirect_to admin_trip_url(@trip) }
        else
          f.html { render :edit }
        end
      end
    end

    def destroy
      @trip.destroy

      respond_to do |f|
        f.html { redirect_to admin_trips_url }
      end
    end

    private

    def trip_params
      params.require(:trip).permit(:number_trip, :arrival_time, :departure_time, :service_type_id, :train_type_id, :company_id)
    end

    def set_trip
      @trip = Trip.find(params[:id])
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @user = current_user
  end

  def about; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[edit update show destroy]

  def index
    @tickets = Ticket.by_user(current_user).order(created_at: :desc)
  end

  def show; end

  def new
    @employee_ticket = Employee.all.pluck(:id).to_a.sample
    @passenger_by_user = Passenger.all.by_user(current_user)
    @ticket = Ticket.new(employee_id: @employee_ticket)
  end

  def edit
    @passenger_by_user = Passenger.all.by_user(current_user)

  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.employee_id ||= Employee.all.pluck(:id).to_a.sample
    @passenger_by_user = Passenger.all.by_user(current_user)
    if @ticket.save
      p @ticket
      redirect_to ticket_url(@ticket)
    else
      render :new
    end
  end

  def update
    @passenger_by_user = Passenger.all.by_user(current_user)

    respond_to do |f|
      if @ticket.update(ticket_params)
        f.html { redirect_to ticket_url(@ticket) }
      else
        f.html { render :edit }
      end
    end
  end

  def destroy
    @passenger_by_user = Passenger.all.by_user(current_user)

    @ticket.destroy

    respond_to do |f|
      f.html { redirect_to tickets_url }
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:passenger_id, :trip_id, :employee_id)
  end

  def set_ticket
    @ticket = Ticket.by_user(current_user).where(id: params[:id]).first
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = params[:q].blank? ? Trip.all.order(created_at: :desc) : Trip.all.number_trip_asc
  end

  def show
    @trip = Trip.where(id: params[:id]).first
  end

  def search
    @trip = Trip.where("number_trip = ?", params[:q]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/train_types_helper.rb
module TrainTypesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/admin/trips/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: [ :admin, @trip ], :html => {class: "form-horizontal", role: "form"}) do |form| %>
      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :number_trip %>
        </div>
        <div class="col-sm-3">
          <%= form.number_field :number_trip, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :arrival_time %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :arrival_time, rows: 10, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :departure_time %>
        </div>
        <div class="col-sm-3">
          <%= form.text_field :departure_time, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :service_type_id %>
        </div>
        <div class="col-sm-3">
          <%= form.number_field :service_type_id, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :train_type_id %>
        </div>
        <div class="col-sm-3">
          <%= form.number_field :train_type_id, rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= form.label :company_id %>
        </div>
        <div class="col-sm-3">
          <%= form.number_field :company_id, rows: 10, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= form.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/trips/_trip.html.erb
<div class="row">
  <div class="col-xs-8">
    <div class="well well-lg">
      <div class="review-title">
        <p>
          <strong>Number of trip:</strong>
          <%= trip.number_trip %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Arrival:</strong>
          <%= trip.arrival_time %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Departure:</strong>
          <%= trip.departure_time %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Service type:</strong>
          <%= trip.name_service_type %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Train type:</strong>
          <%= trip.name_train_type %>
        </p>
      </div>
      <div class="review-title">
        <p>
          <strong>Company:</strong>
          <%= trip.name_company %>
        </p>
      </div>
    </div>
  </div>
</div>
<div>
  <%= link_to "Back", trips_path %>
</div>

app/views/admin/trips/edit.html.erb
<h1>Edit passenger</h1>
<%= render 'admin/trips/form', trip: @trip%>
<br>
<div>
  <%= link_to "Back to other trips", admin_trips_path, class: "btn btn-xs btn-primary" %>
</div>

app/views/admin/trips/index.html.erb
<h1>Table of trips</h1>
<h3>Click on number of trip to see more information about trip</h3>
<style>
    table, th, td {
        border: 2px solid white;
    }

    th, td {
        background-color: #DCDCDC;
    }
</style>

<form class="form-inline my-2 my-lg-0" action="/search">
  <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search trip number" aria-label="Search">
  <br><button class="btn btn-online-success my-2 my-sm-0" type="submit">Search</button><br><br>
</form>

<div class="ui-select selBox">
  <%= form_tag(admin_trips_path, method: 'get') do %>
    <select style="width: 210px; height: 35px;" name="q" class="form-control">
      <option value="None">-Select-</option>
      <option name="trip" value="trip">Order by number of trip</option>
      <option value="">Order by created_at</option>
    </select>
    <button class="btn btn-online-success my-2 my-sm-0" type="submit">Search</button>
  <% end %>
  <br>
</div>

<table class="table">
  <tr>
    <th scope="col">ID Trip</th>
    <th scope="col">Number of trip</th>
    <th scope="col">Arrival time</th>
    <th scope="col">Departure time</th>
    <th scope="col">Class of service</th>
    <th scope="col">Class of train type</th>
    <th scope="col">Name of carrier company</th>
  </tr>
  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.id %></td>
      <td><%= link_to trip.number_trip, admin_trip_path(trip) %></td>
      <td><%= trip.arrival_time %></td>
      <td><%= trip.departure_time %></td>
      <td><%= trip.name_service_type %></td>
      <td><%= trip.name_train_type %></td>
      <td><%= trip.name_company %></td>
    </tr>
  <% end %>
</table>

app/views/admin/trips/new.html.erb
<h1>New trip</h1>
<%= render 'admin/trips/form', trip: @trip %>
<br>
<div>
  <%= link_to "Back to other trip", admin_trips_path, class: "btn btn-xs btn-primary" %>
</div>

app/views/admin/trips/show.html.erb
<%= render 'admin/trips/trip', trip: @trip %>
<div>
  <%= link_to "Back", admin_trips_path, class: "btn btn-xs btn-primary" %>
  <%= link_to "Edit", edit_admin_trip_path(@trip), class: "btn btn-xs btn-success" %>
  <%= button_to "Delete", admin_trip_path(@trip), method: :delete, class: "btn btn-xs btn-danger" %>
</div>